version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - MJ_APIKEY_PUBLIC=466f87960616cd45aac376cf96323c43
      - MJ_APIKEY_PRIVATE=fadc395b52966871a88f8f306c5a946b
    ports:
      - "8000:8000"
    volumes:
      - ./stagelite:/stagelite
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver --settings=stagelite.settings 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             celery -A topics worker -l info"
    volumes:
      - ./stagelite:/stagelite
    env_file:
      - ./.env.dev
    ports:
      - "465:465"
    depends_on:
      - db
      - redis
      - rabbitmq
      - app
  celery_flower:
    restart: always
    build:
      context: .
    ports:
      - "5555:5555"
    env_file:
      - ./.env.dev
    command: "celery -A topics flower"
    volumes:
      - ./stagelite:/stagelite
    depends_on:
      - db
      - redis
      - app
      - rabbitmq
      - celery
  frontend:
    build:
      context: .
      dockerfile: stagelite/frontend/Dockerfile
    ports:
      - "3000:3000"
  celerybeat:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             celery -A topics beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
      - celery
volumes:
  pgdata:
