# Generated by Django 3.0.4 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageuser',
            name='user_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='stageuser',
            name='user_notification_preference',
            field=models.CharField(choices=[('a', 'email'), ('b', 'text')], default='a', max_length=1),
        ),
    ]
