# Generated by Django 3.0.4 on 2022-10-25 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20221025_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 9, 1, 32, 410912)),
        ),
    ]
