# Generated by Django 3.0.4 on 2022-10-25 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_auto_20221025_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 10, 36, 44, 191282)),
        ),
    ]
