# Generated by Django 3.0.4 on 2022-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_auto_20221025_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='end_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
